const abi = [
  { inputs: [{ internalType: "address", name: "_trustedForwarder", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { inputs: [], name: "InvalidInitialization", type: "error" },
  { inputs: [], name: "ModuleManagerBase__CallerNotAuthorized", type: "error" },
  { inputs: [], name: "ModuleManagerBase__InvalidModuleAddress", type: "error" },
  { inputs: [], name: "ModuleManagerBase__IsModule", type: "error" },
  { inputs: [], name: "ModuleManagerBase__IsNotModule", type: "error" },
  { inputs: [], name: "ModuleManagerBase__ModuleAmountOverLimits", type: "error" },
  { inputs: [], name: "ModuleManagerBase__ModuleFactoryInvalid", type: "error" },
  { inputs: [], name: "ModuleManagerBase__ModuleNotRegistered", type: "error" },
  { inputs: [], name: "ModuleManagerBase__ModuleUpdateAlreadyStarted", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "_module", type: "address" },
      { internalType: "uint256", name: "_timelockUntil", type: "uint256" },
    ],
    name: "ModuleManagerBase__ModuleUpdateTimelockStillActive",
    type: "error",
  },
  { inputs: [], name: "ModuleManagerBase__OnlyCallableByModule", type: "error" },
  { inputs: [], name: "NotInitializing", type: "error" },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "caller", type: "address" },
    ],
    name: "Orchestrator__CallerNotAuthorized",
    type: "error",
  },
  { inputs: [], name: "Orchestrator__DependencyInjection__ModuleNotUsedInOrchestrator", type: "error" },
  { inputs: [{ internalType: "address", name: "module", type: "address" }], name: "Orchestrator__InvalidModuleType", type: "error" },
  { inputs: [], name: "Orchestrator__InvalidRemovalOfAuthorizer", type: "error" },
  { inputs: [], name: "Orchestrator__InvalidRemovalOfFundingManager", type: "error" },
  { inputs: [], name: "Orchestrator__InvalidRemovalOfPaymentProcessor", type: "error" },
  {
    inputs: [
      { internalType: "address", name: "currentToken", type: "address" },
      { internalType: "address", name: "newToken", type: "address" },
    ],
    name: "Orchestrator__MismatchedTokenForFundingManager",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_address", type: "address" }],
    name: "AuthorizerUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_address", type: "address" }],
    name: "FundingManagerUpdated",
    type: "event",
  },
  { anonymous: false, inputs: [{ indexed: false, internalType: "uint64", name: "version", type: "uint64" }], name: "Initialized", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "module", type: "address" }], name: "ModuleAdded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "module", type: "address" }], name: "ModuleRemoved", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "module", type: "address" },
      { indexed: false, internalType: "uint256", name: "timelockUntil", type: "uint256" },
    ],
    name: "ModuleTimelockStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "address", name: "module", type: "address" }],
    name: "ModuleUpdateCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orchestratorId_", type: "uint256" },
      { indexed: false, internalType: "address", name: "fundingManager", type: "address" },
      { indexed: false, internalType: "address", name: "authorizer", type: "address" },
      { indexed: false, internalType: "address", name: "paymentProcessor", type: "address" },
      { indexed: false, internalType: "address[]", name: "modules", type: "address[]" },
      { indexed: false, internalType: "address", name: "governor", type: "address" },
    ],
    name: "OrchestratorInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "address", name: "_address", type: "address" }],
    name: "PaymentProcessorUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "MODULE_UPDATE_TIMELOCK",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "authorizer",
    outputs: [{ internalType: "contract IAuthorizer_v1", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IAuthorizer_v1", name: "authorizer_", type: "address" }],
    name: "cancelAuthorizerUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IFundingManager_v1", name: "fundingManager_", type: "address" }],
    name: "cancelFundingManagerUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module_", type: "address" }],
    name: "cancelModuleUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IPaymentProcessor_v1", name: "paymentProcessor_", type: "address" }],
    name: "cancelPaymentProcessorUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module_", type: "address" }],
    name: "executeAddModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module_", type: "address" }],
    name: "executeRemoveModule",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IAuthorizer_v1", name: "newAuthorizer", type: "address" }],
    name: "executeSetAuthorizer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IFundingManager_v1", name: "newFundingManager", type: "address" }],
    name: "executeSetFundingManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IPaymentProcessor_v1", name: "newPaymentProcessor", type: "address" }],
    name: "executeSetPaymentProcessor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "fundingManager",
    outputs: [{ internalType: "contract IFundingManager_v1", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [{ internalType: "contract IGovernor_v1", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "orchestratorId_", type: "uint256" },
      { internalType: "address", name: "moduleFactory_", type: "address" },
      { internalType: "address[]", name: "modules", type: "address[]" },
      { internalType: "contract IFundingManager_v1", name: "fundingManager_", type: "address" },
      { internalType: "contract IAuthorizer_v1", name: "authorizer_", type: "address" },
      { internalType: "contract IPaymentProcessor_v1", name: "paymentProcessor_", type: "address" },
      { internalType: "contract IGovernor_v1", name: "governor_", type: "address" },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module_", type: "address" }],
    name: "initiateAddModuleWithTimelock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module_", type: "address" }],
    name: "initiateRemoveModuleWithTimelock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IAuthorizer_v1", name: "newAuthorizer", type: "address" }],
    name: "initiateSetAuthorizerWithTimelock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IFundingManager_v1", name: "newFundingManager", type: "address" }],
    name: "initiateSetFundingManagerWithTimelock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "contract IPaymentProcessor_v1", name: "newPaymentProcessor", type: "address" }],
    name: "initiateSetPaymentProcessorWithTimelock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module", type: "address" }],
    name: "isModule",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "forwarder", type: "address" }],
    name: "isTrustedForwarder",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "listModules",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "module", type: "address" }],
    name: "moduleAddressToTimelock",
    outputs: [
      { internalType: "bool", name: "timelockActive", type: "bool" },
      { internalType: "uint256", name: "timelockUntil", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "moduleFactory",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [], name: "modulesSize", outputs: [{ internalType: "uint8", name: "", type: "uint8" }], stateMutability: "view", type: "function" },
  {
    inputs: [],
    name: "orchestratorId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "paymentProcessor",
    outputs: [{ internalType: "contract IPaymentProcessor_v1", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
];

export default abi;
